config/routes.rb
Rails.application.routes.draw do

  

   
  devise_scope :admin do
    authenticated :admin do
      resources :customers do
        member do
          put 'switch', to: 'customers#status_switch'
          get 'edit', to: 'customers#edit'
        end
      end
      
      resources :products
      resources :orders
      
      root 'admins#index', as: :authenticated_admins_root
    end
     
  end
  
  devise_for :admins
  root 'admins#welcome'
end

app/views/admins/index.html.erb
<body class = "bg1"> 
<div class="time"><p><%= Time.zone.now.strftime("%l:%M %p") %></p></div>
<div class="greeting"><p>Hello, Manager!</p></div>

<table align="center">
<tr>
    <td class="index_buttons_table"><%= link_to "Customers", customers_path, class: 'btn btn-default btn-sm' %></td>
    <td class="index_buttons_table"><%= link_to "Orders", orders_path, class: 'btn btn-default btn-sm' %></td>
    <td class="index_buttons_table"><%= link_to "Products", products_path, class: 'btn btn-default btn-sm' %></td><!-- nag-eerror siya pag ginawa ko siyang button hUHUHU -->
    </tr>
</table>
</body>

app/views/admins/welcome.html.erb
<html>
<head>
  
</head>  

<body class = "bg"> 
<br/>
<div class="container">
<div class="border-form-div"> <!-- col-md-12-->
<img src = "https://78.media.tumblr.com/8c48b56225275b3f2b97d60a2a5c1f53/tumblr_p8d78pze6S1w4edkko1_1280.png", class="logo">
 
          <center><%= button_to "Log in as Admin", new_admin_session_path, :class => "adminlogin" %></center>
          <center><button class ="sstafflogin">Log in as Sales Staff</button></center>
          <center><button class ="istafflogin">Log in as Inventory Staff</button></center>
</div>
<footer>
<div class="copyright col-md-12"><p><center>Copyright © 2018 Milestone Corporation</center></p></div>
</div>
</footer>
</body>
</html>