config/routes.rb
Rails.application.routes.draw do

  

   
  devise_scope :admin do
    authenticated :admin do
      resources :customers do
        member do
          put 'switch', to: 'customers#status_switch'
          get 'edit', to: 'customers#edit'
        end
      end
      
      resources :products
      resources :orders
      
      root 'admins#index', as: :authenticated_admins_root
    end
     
  end
  
  devise_for :admins
  root 'admins#welcome'
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :customer
    
    has_many :order_lines, inverse_of: :order, dependent: :delete_all
    has_many :products, through: :order_lines
    accepts_nested_attributes_for :order_lines, allow_destroy: true, reject_if: :reject_order_lines
    
    has_many :payments, inverse_of: :order, dependent: :delete_all
    has_many :customers, through: :payments
    accepts_nested_attributes_for :payments, allow_destroy: true, reject_if: :reject_payments
    
    private
        def reject_order_lines
            false
        end
        def reject_payments
            false
        end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    include SmartListing::Helper::ControllerExtensions
    helper  SmartListing::Helper

    before_action :get_options_for_select, only: [:new, :edit]
    
    def index
        @selected_month = !params[:month].present? || params[:month] == 0 ? 0 : params[:month]
        @selected_year = !params[:year].present? || params[:year] == 0 ? 0 : params[:year]
        
        order_scope = Order.all
        if @selected_month != 0 && @selected_year != 0
            order_scope = Order.where(
                'EXTRACT(MONTH FROM ORDER_DATE) = ? AND EXTRACT(YEAR FROM ORDER_DATE) = ?',
                @selected_month,
                @selected_year
            )
        end
        order_scope.order(order_date: :desc)
        @orders = smart_listing_create :orders, order_scope, partial: 'list'
    end

    def new
        @order = Order.new
    end
    
    def create
       @order = Order.new order_params
       if @order.save
           redirect_to orders_path(@order)
       else
           render :new
       end
    end
    
    def show
        @order = Order.find params[:id]
    end
    
    def edit
        @order = Order.find params[:id]
    end
    
    def update
        @order = Order.find params[:id]
        if @order.update order_params
            redirect_to orders_path(@order)
        else
            render :edit
        end
    end
    
    def destroy
       @order = Order.find params[:id]
       @order.destroy
    end
    
    private
        def order_params
            params.require(:order).permit!
        end
        
        def get_options_for_select
            @customer_opts = Customer.pluck(:name, :company, :id).map { |arr| [ "#{arr[0]} (#{arr[1]})", arr[2] ] }
            @product_opts = Product.pluck(:name, :id)
            @order_status_opts = ['Received', 'Returned', 'Replacement', 'Unpaid', 'Partially paid', 'Paid']
            @order_line_status_opts = ['Received', 'Returned', 'Replacement']
            @payment_type_opts = ['Cash', 'Check', 'Credit']
        end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for @order do |order| %>

    <div class="row">
        <div class="col-md-8">
            <!-- Customer -->
            <div class="form-group">
                <label>Customer</label>
                <%= 
                    order.select :customer_id, @customer_opts,
                        { label_method: :first, value_method: :last },
                        { class: 'form-control' }
                %>
            </div>
        </div>
        
        <div class="col-md-4">
            <!-- Order date -->
            <%= order.input :order_date, as: :date, html5: true %>
        </div>
    </div>
    
    <!-- Order lines -->
    <div class="form-group">
        <label>Products</label>
        <table class="table" id="table-orderLines">
            <thead>
                <th>Product</th>
                <th>Qty.</th>
                <th>Discount Rate</th>
                <th>Status</th>
                <th>Date for status</th>
                <th></th>
            </thead>
            <tbody>
                <%= order.simple_fields_for :order_lines do |order_line| %>
                    <%= render 'order_line_fields', order_line: order_line %>
                <% end %>
            </tbody>
        </table>
        <%=
            link_to_add_association '+ Add Product', order, :order_lines,
            form_name: 'order_line',
            data: {
                'association-insertion-node': '#table-orderLines tbody',
                'association-insertion-method': 'append'
            }
        %>
    </div>
    
    <div class="row">
        <div class="col-md-4">
            <!-- Payment due date -->
            <%= order.input :payment_due_date, as: :date, html5: true %>
        </div>
        <div class="col-md-3">
            <!-- Discount rate -->
            <%= order.input :discount_rate, as: :decimal %>
        </div>
        <div class="col-md-3">
            <!-- Status -->
            <div class="form-group">
                <label>Status</label>
                <%= 
                    order.select :status, @order_status_opts,
                        { label_method: :first, value_method: :first },
                        { class: 'form-control' }
                %>
            </div>
        </div>
    </div>
    
    
    
    <!-- Payments -->
    <div class="form-group">
        <label>Payments</label>
        <table class="table" id="table-payments">
            <thead>
                <th>Amount Paid</th>
                <th>Payment Type</th>
                <th>Date Paid</th>
                <th></th>
            </thead>
            <tbody>
                <%= order.simple_fields_for :payments do |payment| %>
                    <%= render 'payment_fields', payment: payment %>
                <% end %>
            </tbody>
        </table>
        <%=
            link_to_add_association '+ Add Payment', order, :payments,
            form_name: 'payment',
            data: {
                'association-insertion-node': '#table-payments tbody',
                'association-insertion-method': 'append'
            }
        %>
    </div>
    
    <div class="form-group">
        <%= order.submit 'Save', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', orders_path, class: 'btn btn-default' %>
    </div>
    
<% end %>

app/views/orders/_list.html.erb
<div class="action-bar">
    <div class="record-count-container">
        <h4><%= smart_listing.count %> record(s) found.</h4>
    </div>
    <div class="new-order-link-container">
        <%= link_to new_order_path, class: 'btn' do %>
            <i class="<%= smart_listing_config.classes(:icon_new) %>"></i>
            New
        <% end %>
    </div>
</div>

<% unless smart_listing.empty? %>
    <table class="table table-striped table-bordered">
        <thead>
            <th><%= smart_listing.sortable 'Invoice No.', :id %></th>
            <th><%= smart_listing.sortable 'Date', :order_date %></th>
            <th>Customer</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Note</th>
            <th></th>
        </thead>
        <tbody>
            <% smart_listing.collection.each do |order| %>
                <tr>
                    <td>
                        <%= order.id %>
                    </td>
                    <td>
                        <%= order.order_date %> <!-- strftime('%m/%d/%y') -->
                    </td>
                    <td>
                        <%= "#{order.customer.name} (#{order.customer.company})" %>
                    </td>
                    <td>
                        <ul class="list-unstyled">
                            <% order.order_lines.each do |order_line| %>
                                <li><%= order_line.product.name %></li>
                            <% end %>
                        </ul>
                    </td>
                    <td>
                        <ul class="list-unstyled">
                            <% order.order_lines.each do |order_line| %>
                                <li><%= order_line.quantity_of_product %></li>
                            <% end %>
                        </ul>
                    </td>
                    <td>
                        <ul class="list-unstyled">
                            <% order.order_lines.each do |order_line| %>
                                <li>
                                    <% if order_line.status == 'Received' %>
                                        N/A
                                    <% else %>
                                        <span class="text-danger">
                                            <%= "#{order_line.status} (#{order_line.date_for_the_status})" %>
                                        </span>
                                    <% end %>
                                </li>
                            <% end %>
                        </ul>
                    </td>
                    <td>
                        <%= link_to 'Edit', edit_order_path(order) %>
                        <!-- &nbsp;&nbsp;|&nbsp;&nbsp; -->
                        <%#= link_to 'View', order_path(order) %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= smart_listing.paginate %>
<% else %>
    <p class="text-warning">No records!</p>
<% end %>

app/views/orders/_order_line_fields.html.erb
<tr class="order-line-item">
    <td>
        <%=
            order_line.select :product_id, @product_opts,
                { label_method: :first, value_method: :last },
                { class: 'form-control' }
        %>
    </td>
    <td>
        <%= 
            order_line.input :quantity_of_product,
                as: :integer, label: false, wrapper: false
        %>
    </td>
    <td>
        <%= 
            order_line.input :discount_rate,
                as: :decimal, label: false, wrapper: false
        %>
    </td>
    <td>
        <%=
            order_line.select :status, @order_line_status_opts,
                { label_method: :first, value_method: :last },
                { class: 'form-control' }
        %>
    </td>
    <td>
        <%= 
            order_line.input :date_for_the_status,
                as: :date, html5: true, label: false, wrapper: false
        %>
    </td>
    <td>
        <%= 
            link_to_remove_association 'Remove', order_line,
                wrapper_class: 'order-line-item',
                class: 'text-danger'
        %>
    </td>
</tr>

app/views/orders/_orderline_fields.html.erb
<tr class="order-line-item">
    <td>
        <%=
            orderline.select :product_id, @product_opts,
                { label_method: :first, value_method: :last },
                { class: 'form-control' }
        %>
    </td>
    <td>
        <%= 
            orderline.input :quantity_in_kg,
                as: :integer, label: false, wrapper: false
        %>
    </td>
    <td>
        <%= 
            orderline.input :discount_rate,
                as: :decimal, label: false, wrapper: false
        %>
    </td>
    <td>
        <%=
            orderline.select :status, @orderline_status_opts,
                { label_method: :first, value_method: :last },
                { class: 'form-control' }
        %>
    </td>
    <td>
        <%= 
            orderline.input :status_date,
                as: :date, html5: true, label: false, wrapper: false
        %>
    </td>
    <td>
        <%= 
            link_to_remove_association 'Remove', orderline,
                wrapper_class: 'order-line-item',
                class: 'text-danger'
        %>
    </td>
</tr>

app/views/orders/_payment_fields.html.erb
<tr class="payment-item">
    <td>
        <%= 
            payment.input :amount_paid,
                as: :decimal, label: false, wrapper: false
        %>
    </td>
    <td>
        <%=
            payment.select :payment_type, @payment_type_opts,
                { label_method: :first, value_method: :last },
                { class: 'form-control' }
        %>
    </td>
    <td>
        <%= 
            payment.input :date_paid,
                as: :date, html5: true, label: false, wrapper: false
        %>
    </td>
    <td>
        <%= 
            link_to_remove_association 'Remove', payment,
                wrapper_class: 'payment-item',
                class: 'text-danger'
        %>
    </td>
</tr>

app/views/orders/edit.html.erb
<h3>Edit Order</h3>
<%= render 'form' %>

app/views/orders/index.html.erb
    <h1> <center>Orders Page</center><br/></h1>
<div class="filter-form-container">
    <%= form_tag( { controller: 'orders', action: 'index' }, { method: :get, enforce_utf8: false } ) do %>
        <div class="fields-container form-inline">
            <%= 
                select_tag :month,
                    options_for_select(
                        Date::MONTHNAMES.each_with_index.collect { |m, i| [ m.nil? ? 'Select month...' : m , i] },
                        @selected_month
                    ),
                    class: 'form-control',
                    onchange: <<-js
                        selectMonth = $(this.form).find('select[name="month"]');
                        selectYear = $(this.form).find('select[name="year"]');
                        if (selectMonth.val() != 0 && selectYear.val() != 0) this.form.submit();
                    js
            %>
            <%= 
                select_tag :year,
                    options_for_select(
                        [['Select year...', 0]] + Date.today.year.downto(2000).to_a,
                        @selected_year
                    ),
                    class: 'form-control',
                    onchange: <<-js
                        selectMonth = $(this.form).find('select[name="month"]');
                        selectYear = $(this.form).find('select[name="year"]');
                        if (selectMonth.val() != 0 && selectYear.val() != 0) this.form.submit();
                    js
            %>
        </div>
        <div class="info-container form-inline">
            <span class="filter-text-container">
                <% if @selected_month != 0 && @selected_year != 0 %>
                    Showing records within <strong><%= "#{Date::MONTHNAMES[@selected_month.to_i]} #{@selected_year}" %></strong>.
                    <%= link_to 'Clear filter', orders_path, class: 'btn-link clear-filter-link' %>
                <% else %>
                    Showing all records.
                    <%= 
                        link_to 'Go to current month & year', orders_path(month: Date.today.month, year: Date.today.year),
                            class: 'btn-link clear-filter-link'
                    %>
                <% end %>
            </span>
            
           
            <span class="orders-info-container">
                <span class="unpaid-orders-text text-info">
                    <strong>Unpaid orders: 0</strong>
                </span>
                <% if @selected_month != 0 && @selected_year != 0 %>
                    <span class="orders-done-within-month-text text-info">
                        <strong>Orders done within month: 0</strong>
                    </span>
                <% end %>
            </span>
        </div>
    <% end %>
</div>

<%= smart_listing_render :orders %>

app/views/orders/index.js.erb
<%= smart_listing_update(:orders) %>

app/views/orders/new.html.erb
<h3>New Order</h3>
<%= render 'form' %>

app/views/orders/show.html.erb
<h3>View Order</h3>
<%= link_to '< Go back', orders_path, class: 'btn btn-link' %>
<div class="panel panel-default order-container">
    <div class="panel-body">
        <div class="company-info-container">
            <div class="company-logo-container">
                <img src = "https://78.media.tumblr.com/8c48b56225275b3f2b97d60a2a5c1f53/tumblr_p8d78pze6S1w4edkko1_1280.png">
            </div>
            <div class="company-text-container">
                <h5 class="company-name-text">RIGHT CATCH TRADING</h5>
                <div>
                    7/F Finman Bldg., 131 Tordesillas Street, Salcedo Village, Bel Air, Makati City<br>
                    Princess K. Lim – Proprietor<br>
                    NON VAT Reg. TIN 219-846-017-000
                </div>
            </div>
        </div>
        <div class="invoice-info-container">
            <span>SALES INVOICE</span>
            <span class="pull-right">NO. <%= @order.id %></span>
        </div>
        <div class="order-info-container">
            <div class="customer-details-container">
                <table>
                    <tbody>
                        <tr>
                            <td class="details-label" rowspan="4">Sold to:</td>
                            <td><%= @order.customer.name %></td>
                        </tr>
                        <tr>
                            <td><%= @order.customer.company %></td>
                        </tr>
                        <tr>
                            <td><%= @order.customer.home_address %></td>
                        </tr>
                        <tr>
                            <td><%= @order.customer.phone %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="payment-details-container">
                <table>
                    <tbody>
                        <tr>
                            <td>Issue date:</td>
                            <td><%= @order.order_date.strftime('%m/%d/%y') unless @order.order_date.nil? %></td>
                        </tr>
                        <tr>
                            <td>Due date:</td>
                            <td><%= @order.payment_due_date.strftime('%m/%d/%y') unless @order.payment_due_date.nil? %></td>
                        </tr>
                        <tr>
                            <td>Status:</td>
                            <td><%= @order.status %></td>
                        </tr>
                        <tr>
                            <td>Form of payment:</td>
                            <td><%= @order.payments.first.payment_type unless @order.payments.first.nil? %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="orderline-table-container">
            <table class="table table-bordered table-sm">
                <thead>
                    <th>Qty.</th>
                    <th>Unit</th>
                    <th>Items</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Amount</th>
                </thead>
                <tbody>
                    <% @order.order_lines.each do |orderline| %>
                        <tr class="orderline-item">
                            <td>
                                <%= orderline.quantity_of_product %>
                            </td>
                            
                            <td>
                                <%= orderline.product.name %>
                            </td>
                            <td>
                                <%= number_with_precision(orderline.product.base_price, precision: 2) %>
                            </td>
                            <td>
                                <%=
                                    number_with_precision(
                                        orderline.discount_rate,
                                        precision: 2
                                    )
                                %>
                                (<%= number_with_precision(orderline.discount_rate || 0, precision: 2) %>%)
                            </td>
                            <!--<td>
                                <%#= number_with_precision(@order.order_lines.total_amount || 0, precision: 2) %>
                            </td>-->
                        </tr>
                    <% end %>
                    <tr class="summary-row">
                        <td colspan="5">Total Amount</td>
                        <td>
                            <%= number_with_precision(@order.total_price, precision: 2) %>
                        </td>
                    </tr>
                    <tr class="summary-row">
                        <td colspan="5">Order Discount</td>
                        <td>
                            <%= number_with_precision(@order.total_discount_amount, precision: 2) %>
                        </td>
                    </tr>
                    <tr class="summary-row">
                        <td colspan="5">Amount Paid</td>
                        <td>
                            <%= number_with_precision(@order.total_amount_paid, precision: 2) %>
                        </td>
                    </tr>
                    <tr class="summary-row">
                        <td colspan="5">Amount Due</td>
                        <td>
                            <%= number_with_precision(@order.total_amount_due, precision: 2) %>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="signature-container">
            <div class="agreement-text">
                Received the above items in good order and conditions
            </div>
            <div class="signature-space pull-right">
                Signature
            </div>
        </div>
    </div>
</div>