config/routes.rb
Rails.application.routes.draw do

  

   
  devise_scope :admin do
    authenticated :admin do
      resources :customers do
        member do
          put 'switch', to: 'customers#status_switch'
          get 'edit', to: 'customers#edit'
        end
      end
      
      resources :products
      resources :orders
      
      root 'admins#index', as: :authenticated_admins_root
    end
     
  end
  
  devise_for :admins
  root 'admins#welcome'
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :order_lines
    has_many :orders, through: :order_lines
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    include SmartListing::Helper::ControllerExtensions
    helper  SmartListing::Helper
    
    before_filter :find_product, except: [:index, :new, :create]

    def index
      @products = smart_listing_create(:products, 
        Product.all, 
        partial: "products/list",
        default_sort: {name: "asc"})
        
      respond_to do |format|
        format.html
        format.js
      end
    end
    
    def new
      @product = Product.new
    end
    
    def create
      @product = Product.create(product_params)
    end
    
    def edit
    end
    
    def update
      if @product.update(product_params)
         redirect_to products_path
        else
          render :edit
      end
    end
    
    def destroy
      @user.destroy
    end
    
    def status_switch
      @product.toggle(:status)
    end

    private
    def find_product
      @product = Product.find(params[:id])
    end
    
    def product_params
      params.require(:product).permit(:name, :threshold, :base_price,
                                    :quantity, :status)
                                   #or include :session_id    ?
    end
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<td colspan="9">
  <%= form_for object, url: object.new_record? ? products_path : product_path(object),  
    remote: true, html: {class: "form-horizontal"} do |f| %>
    <label>Name:</label>
    <%= f.text_field :name, required: true %> 
    <br>

    <label>Threshold:</label>
    <%= f.text_field :threshold, required: true %> 
    <br>
    
    <label>Base Price:</label>
    <%= f.text_field :base_price, required: true %> 
    <br>
    
    <label>Quantity:</label
    <%= f.text_field :quantity, required: true %> 
    <br>
    
    <%= f.label "Active product?" %> 
    <%= f.check_box :status %> <br />
    
    <br><br>
    <%= f.submit "Save", class: "btn btn-primary" %>
      <button class="btn btn-link cancel">Cancel</button>
  <% end %>
</td>

app/views/products/_list.html.erb
<% unless smart_listing.empty? %>
  <table id="product" class="table table-striped">
    <thead>
      <th class="col-md-3">
        <%= smart_listing.sortable "Name", "name" %>
      </th>
      <th class="col-md-2">
        <%= "Threshold" %>
      </th>
     
      <th class="col-md-2">
        <%= "Base Price" %>
      </th>
      <th class="col-md-2">
        <%= "Quantity" %>
      </th>
      <th class="col-md-2">
        <%= smart_listing.sortable "Active?", "status" %>
      </th>
      <th class="col-md-1">
      </th>
    </thead>
    <tbody>
      <% smart_listing.collection.each do |o| %>
        <tr class="editable" data-id="<%= o.id %>">
          <%= smart_listing.render object: o, partial: "products/product", locals: {object: o} %>
        </tr>
      <% end %>
      <%= smart_listing.item_new colspan: 9, link: new_product_path %>
    </tbody>
  </table>
  <%= smart_listing.paginate %>
  <%= smart_listing.pagination_per_page_links %>
<% else %>
  <p class="warning">No records!</p>
<% end %>

app/views/products/_product.html.erb
<td>
  <%= object.name %>
</td>
<td>
  <%= object.threshold %>
</td>
<td>
  <%= object.base_price %>
</td>
<td>
  <%= object.quantity %>
</td>
<td>
  <%= object.status %>
</td>
<td class="actions">
  <%= smart_listing_item_actions [
      
      { name: :edit, url: edit_product_path(object), icon: "glyphicon glyphicon-pencil", method: :get, remote: true }
    ] %>
</td>

app/views/products/add_supply.html.erb
<td colspan="9">
  <%= form_for object, url: object.new_record? ? products_path : product_path(object),  
    remote: true, html: {class: "form-horizontal"} do |f| %>
    <label>Quantity:</label>
    <%= f.text_field :quantity %> 
    <br>

    <br><br>
    <%= f.submit "Save", class: "btn btn-primary" %>
      <button class="btn btn-link cancel">Cancel</button>
  <% end %>
</td>

app/views/products/create.js.erb
<%# create.js.erb %>
<%= smart_listing_item :products, :create, @product, 
                       @product.valid? ? "products/product" : "products/form" %>

app/views/products/edit.html.erb
<%= render 'form', product: @product%> 

app/views/products/edit.js.erb
<%# edit.js.erb %>
<%= smart_listing_item :products, :edit, @product, "products/form" %>

app/views/products/index.html.erb
<div>
    <h1> <center>Products Page</center><br/></h1>
    <%= smart_listing_render(:products) %>
</div>

<!-- 
READ THIS IF YOU GET BACK, VERON:
kulang ng:
- destroy.js.erb
- edit.html.erb
- edit.js.erb
- status_switch.js.erb
- update.js.erb

needs refinement:
- _product.html.erb -- doesnt want to notice the path for switching product status
- bakit yung active/status ay number
- status is a varchar/string -- change to boolean or tinyint in migration
-->

app/views/products/index.js.erb
<%= smart_listing_update(:products) %>

app/views/products/new.html.erb
<%= render 'form', product: @product %>

app/views/products/new.js.erb
<%# new.js.erb %>
<%= smart_listing_item :products, :new, @product, "products/form" %>

app/views/products/status_switch.js.erb
<%= smart_listing_item(:products, :update, @product, @product.valid? ? "products/product" : "" ) %>

app/views/products/update.js.erb
<%# update.js.erb %>
<%= smart_listing_item :products, :update, @product, 
                       @product.valid? ? "products/product" : "product/form" %>