config/routes.rb
Rails.application.routes.draw do

  

   
  devise_scope :admin do
    authenticated :admin do
      resources :customers do
        member do
          put 'switch', to: 'customers#status_switch'
          get 'edit', to: 'customers#edit'
        end
      end
      
      resources :products
      resources :orders
      
      root 'admins#index', as: :authenticated_admins_root
    end
     
  end
  
  devise_for :admins
  root 'admins#welcome'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Right Catch Trading</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% unless controller_name == 'admins' || action_name == 'new' %>
        <header>
          
  <p class="navbar-text pull-right"> 
  <div id="header"><div class="header-cont"><div class="header">
    <% if admin_signed_in? %>
      <img src = "https://78.media.tumblr.com/8c48b56225275b3f2b97d60a2a5c1f53/tumblr_p8d78pze6S1w4edkko1_1280.png", class="hlogo">
    &nbsp;<%= link_to "Products", products_path, method: :get, :class => 'navbar-link'  %> 
    &nbsp; &nbsp;<%= link_to "Orders", orders_path, method: :get, :class => 'navbar-link'  %>
      &nbsp; &nbsp; <%= link_to "Customers", customers_path, method: :get, :class => 'navbar-link'  %> 
                
      
       &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
      Logged in as <strong><%= current_admin.email %>
      &nbsp; &nbsp;&nbsp; <%= link_to "Log Out", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>          
    <% end %>
  </div> </div> </div> </p> 
<div class="container">          
        </header>
  <% end %>
</head>
<body>
 

<% if notice %>
<p class="alert alert-success alert-dismissible"><%= notice %><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
<% end %>
<% if alert %>
<p class="alert alert-danger alert-dismissible"><%= alert %><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
<% end %>


<div class="<%= "#{controller_name}-controller #{action_name}-view" %> container">
    <%= yield %>
</div>


</div>
</body>
</html>